// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var config = {
  graphqlEndpoint: "https://nkdhnplh2vebvfgjvz3pbbagli.appsync-api.eu-west-1.amazonaws.com/graphql",
  region: "eu-west-1",
  authenticationType: "API_KEY",
  apiKey: "da2-5jdgegpgjjbx3mt4l6fmuqyhta"
};

exports.config = config;
/* No side effect */
