// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var AWS$ReactTemplate = require("./AWS.bs.js");
var AppSyncConfig$ReactTemplate = require("./AppSyncConfig.bs.js");

var client = AWS$ReactTemplate.AppSync[/* createAWSAppSyncClient */0](/* Some */[AppSyncConfig$ReactTemplate.config.graphqlEndpoint], /* Some */[AppSyncConfig$ReactTemplate.config.region], /* Some */[{
        type: AppSyncConfig$ReactTemplate.config.authenticationType,
        apiKey: AppSyncConfig$ReactTemplate.config.apiKey
      }], /* () */0);

exports.client = client;
/* client Not a pure module */
