// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parseItemJson(json) {
  return /* record */[
          /* name */Json_decode.optional((function (param) {
                  return Json_decode.field("name", Json_decode.string, param);
                }), json),
          /* age */Json_decode.optional((function (param) {
                  return Json_decode.field("age", Json_decode.$$int, param);
                }), json),
          /* id */Json_decode.optional((function (param) {
                  return Json_decode.field("id", Json_decode.string, param);
                }), json)
        ];
}

function parseItemsResponseJson(json) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.array(parseItemJson, param);
              }), json);
}

var Decode = /* module */[
  /* parseItemJson */parseItemJson,
  /* parseItemsResponseJson */parseItemsResponseJson
];

exports.Decode = Decode;
/* No side effect */
